[build]
  publish = "."

# Required for Netlify Identity to redirect properly after login
[[redirects]]
  from   = "/admin"
  to     = "/admin/index.html"
  status = 200

# Keep the CMS admin out of search engines
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex"
